# Generated by Django 4.1.2 on 2022-10-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cartitem_product_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_status',
            field=models.CharField(choices=[('W', 'Waiting for payment'), ('C', 'Collecting order'), ('S', 'Sent')], default='W', max_length=1),
        ),
    ]
