# Generated by Django 4.1.2 on 2022-10-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_orderitem_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('W', 'Waiting for payment'), ('C', 'Collecting order'), ('S', 'Sent')], default='W', max_length=1),
        ),
    ]
